# Generated by Django 5.2 on 2025-05-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone_tuteur',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
