# Generated by Django 4.2.20 on 2025-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_participant_phone_tuteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='validator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
